[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/about.html"
  to = "/about"
  status = 301
  force = true

[[redirects]]
  from = "/services.html"
  to = "/services"
  status = 301
  force = true

[[redirects]]
  from = "/portfolio.html"
  to = "/portfolio"
  status = 301
  force = true

[[redirects]]
  from = "/process.html"
  to = "/process"
  status = 301
  force = true

[[redirects]]
  from = "/contact.html"
  to = "/contact"
  status = 301
  force = true

[[redirects]]
  from = "/privacy.html"
  to = "/privacy"
  status = 301
  force = true

[[redirects]]
  from = "/terms.html"
  to = "/terms"
  status = 301
  force = true
